config/routes.rb
Rails.application.routes.draw do
  resources :users

  resource :session, except: [:edit, :update, :show]

  resources :subs
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :string           not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ActiveRecord::Base

  validates :title, :description, :user_id, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator,
    foreign_key: :user_id,
    class_name: :User

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :username, :password_digest, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  has_many :subs

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  # def self.find_by_credentials(username, password)
  #
  # end

  private
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def login!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end

  def require_moderator!(params)
    sub = Sub.find(params[:id])
    redirect_to subs_url unless current_user == sub.moderator
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_username(params[:user][:username])

    if user.nil?
      flash.now[:errors] = "Invalid username"
      render :new
    else
      if user.is_password?(params[:user][:password])
        login!(user)
        render :new #TODO
      else
        flash.now[:errors] = "Invalid login"
        render :new
      end
    end
  end

  def new
    render :new
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_current_user!, except: [:index, :show]
  # before_action :require_moderator!(params), only: [:edit, :update, :destroy]

  def index
    @subs = Sub.all
    render :index
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    
    if @sub.save
      render :show
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def new
    @sub = Sub.new
    render :new
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update_attributes(sub_params)
      render :show
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
    sub = Sub.find(params[:id])
    sub.destroy
    render :new
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_current_user!, except: [:create, :new]

  def index
    @users = User.all
    render :index
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      render :show
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      render :show
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    render :new
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<small><i>
  <% flash.now[:errors].try(:each) do |error| %>
    <%= error %>
  <% end %>
</i></small>

<%= yield %>

</body>
</html>

app/views/subs/_form.html.erb
<% action = (sub.persisted? ? sub_url : subs_url) %>
<% method = (sub.persisted? ? "PATCH" : "POST") %>

<form action="<%= action %>" method="POST">
  <input type="hidden" name="_method" value=<%= method %>>
  <input type="hidden" name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label>Title
    <input  type="text"
            name="sub[title]"
            value="<%= sub.title %>">
  </label>
  <br>
  <label>Description
    <input type="textarea" name="sub[description]">
  </label>
  <br>
  <input type="submit">
</form>

app/views/subs/edit.html.erb
<h1>Edit Sub</h1>
<%= render "form", sub: @sub %>

app/views/subs/index.html.erb
<ul>
<% @subs.each do |sub| %>
  <li><%= link_to "#{sub.title}", sub_url(sub) %></li>
<% end %>
</ul>

app/views/subs/new.html.erb
<h1>Create Sub</h1>
<%= render "form", sub: @sub %>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url : users_url) %>
<% method = (user.persisted? ? "PATCH" : "POST") %>

<form action="<%= action %>" method="POST">
  <input type="hidden" name="_method" value=<%= method %>>
  <input type="hidden" name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label>Username
    <input  type="text"
            name="user[username]"
            value="<%= user.username %>">
  </label>
  <br>
  <label>Password
    <input type="password" name="user[password]">
  </label>
  <br>
  <input type="submit">
</form>

app/views/users/edit.html.erb
<h1>Edit account</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<ul>
<% @users.each do |user| %>
  <li><%= link_to "#{user.username}", user_url(user) %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>Create user account</h1>

<form action="<%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label>Username
    <input type="text" name="user[username]">
  </label>
  <br>
  <label>Password
    <input type="password" name="user[password]">
  </label>
  <br>
  <input type="submit">
</form>

app/views/users/show.html.erb
<h1>Hello, <%= @user.username %></h1>
<%= link_to "Edit your info", edit_user_url(@user) %>
<%= button_to "Delete Account", user_url(@user), method: :delete %>